### PR TITLE
nah-countryJS / city branch

### PR DESCRIPTION
**Pull request by nathanRomad**
city branch of js.

### CODE REVIEW

**Review by powellmad — APPROVED** [review]
looked good! All cities appear and DOM and console clean. 👍

**Comment by nathanRomad** [comment]
hopefully we can merge without any issues. each of my branches has only the automation for each entity.

**Review by powellmad — APPROVED** [review]
Your cities in Antarctica are shown in the DOM, everything looks good. 👍

**Review by bpotts11 — APPROVED** [review]
I see your cities at the bottom. Everything still looks good for Japan and Ireland still. Looks good

**Pull request merged**
