### PR TITLE
Mp auto citizens

### PR DESCRIPTION
**Pull request by powellmad**
Check for citizen cards in Czech! Images and names should appear in DOM. 

```
*commit any changes on current branch*
git fetch --all 
git checkout mp-auto-citizens
```

### CODE REVIEW

**Review by nch66862 — DISMISSED** [review]
Parauge is spelled correctly now. I see everything.

**Review by nathanRomad — DISMISSED** [review]
seeing all changes now. merge conflicts seem to be resolved.  I can see all cards. Great work!

**Review by bpotts11 — APPROVED** [review]
I see everything!!

**Review by nathanRomad — APPROVED** [review]
spelling mistakes are corrected. 
all section cards loaded perfectly.
looks great!

**Review by nch66862 — APPROVED** [review]
I see all 3. Good to go.

**Pull request merged**
