### PR TITLE
Nah citizens js

### PR DESCRIPTION
**Pull request by nathanRomad**
citizens automation is ready to go.. last branch

### CODE REVIEW

**Review by bpotts11 — DISMISSED** [review]
See your citizens populated on your page. Looks good

**Review by nch66862 — DISMISSED** [review]
I see your citizens populate. Looks right!

**Review by nch66862 — APPROVED** [review]
I see your citizens. Good to go.

**Review by bpotts11 — APPROVED** [review]
I see your citizens at the top

**Pull request merged**
