### PR TITLE
Nah landmark js

### PR DESCRIPTION
**Pull request by nathanRomad**
my branch for landmarks is ready to go.

### CODE REVIEW

**Review by bpotts11 — DISMISSED** [review]
I see your landmarks on Antarctica. Looks good

**Review by nch66862 — DISMISSED** [review]
I see your landmarks. Looks good!

**Review by powellmad — DISMISSED** [review]
All landmarks show up with no errors 👍

**Review by bpotts11 — DISMISSED** [review]
looks good

**Review by nch66862 — DISMISSED** [review]
I see your landmarks.

**Review by bpotts11 — APPROVED** [review]
looks good

**Review by nch66862 — APPROVED** [review]
dope

**Pull request merged**
