### PR TITLE
Mp auto landmarks

### PR DESCRIPTION
**Pull request by powellmad**
Check for landmark cards in Czech, please.

### CODE REVIEW

**Review by nathanRomad — DISMISSED** [review]
landmarks loaded great.  It looks like it pulled your main in correctly as well.  I was able to see your cities and landmarks.

**Comment by nathanRomad** [comment]
not a reviewer but your code looks good and landmarks are working!

**Review by nathanRomad — APPROVED** [review]

**Comment by nathanRomad** [comment]
updated and approved with review.

**Review by nch66862 — APPROVED** [review]
I see your landmarks!

**Review by bpotts11 — APPROVED** [review]
Looking good!!

**Pull request merged**
