### PR TITLE
Nc styling for all pages

### PR DESCRIPTION
**Pull request by nch66862**
This should just allow you to drop a photo in the correct place and it will format it for the card size.

'''
git checkout nc-stylingForAllPages

'''

### CODE REVIEW

**Comment by powellmad** [comment]
This is great! Can't wait to see it in the morning.

**Comment by nathanRomad** [comment]
the Japan page looks great Nick!  Hopefully we can get the styling changes to affect my photos as well.. nice work sir.

**Review by nathanRomad — APPROVED** [review]
Let's go!

**Comment by nathanRomad** [comment]
checked again since new changes were made..
looks good to go.

**Review by bpotts11 — APPROVED** [review]
Looks good

**Pull request merged**
