### PR TITLE
Bp added logo pics

### PR DESCRIPTION
**Pull request by bpotts11**
I added the logo pic and fixed all the broken links on the landing page and the nav bar. I reordered my ireland scripts to match.

### CODE REVIEW

**Review by nathanRomad — DISMISSED** [review]
logo is consistent on all pages.  looks good.

**Review by nch66862 — CHANGES_REQUESTED** [review]
go to main.css line number 45 and change the width from 150px to "auto" so it doesnt scrunch up the logo.

**Review by nch66862 — APPROVED** [review]
Logo looks good on all pages!

**Review by nathanRomad — APPROVED** [review]

**Comment by nathanRomad** [comment]
logo is consistent and looks great.  I love that you made one that matches the landing page main photo.

**Pull request merged**
