### PR TITLE
Bp adding js for citizens

### PR DESCRIPTION
**Pull request by bpotts11**
added citizens to the bottom. also changed headline for ireland

### CODE REVIEW

**Review by nathanRomad — DISMISSED** [review]
citizens look great.

**Review by powellmad — DISMISSED** [review]
Ireland citizens appear! 👍

**Review by nathanRomad — APPROVED** [review]
updates look good.

**Review by nch66862 — APPROVED** [review]
May the luck of the irish be with you! Nice.

**Pull request merged**
